function getData()
{
	return [
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"畜禽养殖II,0.54%",
                "value":0.54
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"饲料II,0.66%",
                "value":0.66
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.4
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.45
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.25
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            }
        ],
        "index":1,
        "itemStyle":{
            "color":"#E57373"
        },
        "name":"农林牧渔I,2.3%",
        "value":2.3
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"煤炭开采II,1.05%",
                "value":1.05
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.15
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.03
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.02
            }
        ],
        "index":2,
        "itemStyle":{
            "color":"#EF6492"
        },
        "name":"",
        "value":1.25
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.43
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"化学制品II,2.48%",
                "value":2.48
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.12
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.44
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.1
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.33
            }
        ],
        "index":3,
        "itemStyle":{
            "color":"#B869C8"
        },
        "name":"化工I,3.9%",
        "value":3.9
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#9375CD"
                },
                "name":"钢铁II,1.74%",
                "value":1.74
            }
        ],
        "index":4,
        "itemStyle":{
            "color":"#9375CD"
        },
        "name":"钢铁I,1.74%",
        "value":1.74
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"",
                "value":0.39
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"",
                "value":0.26
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"稀有金属II,0.83%",
                "value":0.83
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"工业金属II,0.63%",
                "value":0.63
            }
        ],
        "index":5,
        "itemStyle":{
            "color":"#7987CB"
        },
        "name":"有色金属I,2.11%",
        "value":2.11
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"元件II,1.72%",
                "value":1.72
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"电子制造II,1.54%",
                "value":1.54
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"光学光电子II,1.76%",
                "value":1.76
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"半导体II,0.94%",
                "value":0.94
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"其他电子II,0.84%",
                "value":0.84
            }
        ],
        "index":6,
        "itemStyle":{
            "color":"#66B5F3"
        },
        "name":"电子I,6.8%",
        "value":6.8
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#50C2F9"
                },
                "name":"白色家电II,1.31%",
                "value":1.31
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#50C2F9"
                },
                "name":"",
                "value":0.17
            }
        ],
        "index":7,
        "itemStyle":{
            "color":"#50C2F9"
        },
        "name":"",
        "value":1.48
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4DD1E2"
                },
                "name":"饮料制造II,1.99%",
                "value":1.99
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4DD1E2"
                },
                "name":"食品加工II,1.76%",
                "value":1.76
            }
        ],
        "index":8,
        "itemStyle":{
            "color":"#4DD1E2"
        },
        "name":"食品饮料I,3.75%",
        "value":3.75
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4FB4AD"
                },
                "name":"",
                "value":0.49
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4FB4AD"
                },
                "name":"",
                "value":0.27
            }
        ],
        "index":9,
        "itemStyle":{
            "color":"#4FB4AD"
        },
        "name":"",
        "value":0.76
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"造纸II,0.54%",
                "value":0.54
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.39
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.21
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.0
            }
        ],
        "index":10,
        "itemStyle":{
            "color":"#81C686"
        },
        "name":"",
        "value":1.14
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"化学制药II,5.92%",
                "value":5.92
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医疗服务II,1.76%",
                "value":1.76
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"生物制品II,3.04%",
                "value":3.04
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医疗器械II,1.85%",
                "value":1.85
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"中药II,2.89%",
                "value":2.89
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医药商业II,1.4%",
                "value":1.4
            }
        ],
        "index":11,
        "itemStyle":{
            "color":"#B0D482"
        },
        "name":"医药生物I,16.86%",
        "value":16.86
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"电力II,2.63%",
                "value":2.63
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"水务II,0.55%",
                "value":0.55
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"环保工程及服务II,1.06%",
                "value":1.06
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"",
                "value":0.09
            }
        ],
        "index":12,
        "itemStyle":{
            "color":"#DCE877"
        },
        "name":"公用事业I,4.33%",
        "value":4.33
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.3
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"高速公路II,0.84%",
                "value":0.84
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.48
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.35
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"港口II,0.56%",
                "value":0.56
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.27
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.17
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.04
            }
        ],
        "index":13,
        "itemStyle":{
            "color":"#FFF177"
        },
        "name":"交通运输I,3.01%",
        "value":3.01
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FCDB62"
                },
                "name":"房地产开发II,4.18%",
                "value":4.18
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FCDB62"
                },
                "name":"",
                "value":0.39
            }
        ],
        "index":14,
        "itemStyle":{
            "color":"#FCDB62"
        },
        "name":"房地产I,4.57%",
        "value":4.57
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.25
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"一般零售II,0.6%",
                "value":0.6
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.17
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.1
            }
        ],
        "index":15,
        "itemStyle":{
            "color":"#FDB84D"
        },
        "name":"",
        "value":1.12
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.38
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.39
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.31
            }
        ],
        "index":16,
        "itemStyle":{
            "color":"#FD8B66"
        },
        "name":"",
        "value":1.08
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#BEBEBE"
                },
                "name":"",
                "value":0.38
            }
        ],
        "index":17,
        "itemStyle":{
            "color":"#BEBEBE"
        },
        "name":"",
        "value":0.38
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"水泥制造II,0.74%",
                "value":0.74
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"",
                "value":0.29
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"",
                "value":0.27
            }
        ],
        "index":18,
        "itemStyle":{
            "color":"#91A4AE"
        },
        "name":"",
        "value":1.3
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.21
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.39
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"基础建设II,0.53%",
                "value":0.53
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.14
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.15
            }
        ],
        "index":19,
        "itemStyle":{
            "color":"#A38680"
        },
        "name":"",
        "value":1.42
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"电源设备II,2.45%",
                "value":2.45
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"高低压设备II,0.85%",
                "value":0.85
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"电气自动化设备II,0.52%",
                "value":0.52
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"",
                "value":0.21
            }
        ],
        "index":20,
        "itemStyle":{
            "color":"#2196F3"
        },
        "name":"电气设备I,4.03%",
        "value":4.03
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.46
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.15
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.12
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.33
            }
        ],
        "index":21,
        "itemStyle":{
            "color":"#02AAF3"
        },
        "name":"",
        "value":1.06
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#01BCD6"
                },
                "name":"计算机应用II,3.51%",
                "value":3.51
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#01BCD6"
                },
                "name":"计算机设备II,0.65%",
                "value":0.65
            }
        ],
        "index":22,
        "itemStyle":{
            "color":"#01BCD6"
        },
        "name":"计算机I,4.16%",
        "value":4.16
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"互联网传媒II,4.38%",
                "value":4.38
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"营销传播II,1.07%",
                "value":1.07
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"文化传媒II,3.24%",
                "value":3.24
            }
        ],
        "index":23,
        "itemStyle":{
            "color":"#009786"
        },
        "name":"传媒I,8.69%",
        "value":8.69
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4EAF51"
                },
                "name":"通信设备II,1.63%",
                "value":1.63
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4EAF51"
                },
                "name":"",
                "value":0.05
            }
        ],
        "index":24,
        "itemStyle":{
            "color":"#4EAF51"
        },
        "name":"通信I,1.68%",
        "value":1.68
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#8CC249"
                },
                "name":"银行II,5.43%",
                "value":5.43
            }
        ],
        "index":25,
        "itemStyle":{
            "color":"#8CC249"
        },
        "name":"银行I,5.43%",
        "value":5.43
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"保险II,2.47%",
                "value":2.47
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"证券II,6.62%",
                "value":6.62
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"多元金融II,0.58%",
                "value":0.58
            }
        ],
        "index":26,
        "itemStyle":{
            "color":"#CCDE37"
        },
        "name":"非银金融I,9.67%",
        "value":9.67
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"汽车整车II,1.4%",
                "value":1.4
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"汽车零部件II,1.46%",
                "value":1.46
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"",
                "value":0.14
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"",
                "value":0.1
            }
        ],
        "index":27,
        "itemStyle":{
            "color":"#FACD20"
        },
        "name":"汽车I,3.1%",
        "value":3.1
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"专用设备II,1.96%",
                "value":1.96
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"通用机械II,0.56%",
                "value":0.56
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.23
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.1
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.04
            }
        ],
        "index":28,
        "itemStyle":{
            "color":"#FF5723"
        },
        "name":"机械设备I,2.89%",
        "value":2.89
    }
]
}