function getData()
{
	return [
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"畜禽养殖II,0.74%",
                "value":0.74
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"饲料II,0.71%",
                "value":0.71
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.44
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.45
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.24
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#E57373"
                },
                "name":"",
                "value":0.0
            }
        ],
        "index":1,
        "itemStyle":{
            "color":"#E57373"
        },
        "name":"农林牧渔I,2.58%",
        "value":2.58
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"煤炭开采II,1.05%",
                "value":1.05
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.16
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.03
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#EF6492"
                },
                "name":"",
                "value":0.02
            }
        ],
        "index":2,
        "itemStyle":{
            "color":"#EF6492"
        },
        "name":"",
        "value":1.26
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.42
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"化学制品II,2.41%",
                "value":2.41
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.14
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.43
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.09
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B869C8"
                },
                "name":"",
                "value":0.32
            }
        ],
        "index":3,
        "itemStyle":{
            "color":"#B869C8"
        },
        "name":"化工I,3.81%",
        "value":3.81
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#9375CD"
                },
                "name":"钢铁II,1.62%",
                "value":1.62
            }
        ],
        "index":4,
        "itemStyle":{
            "color":"#9375CD"
        },
        "name":"钢铁I,1.62%",
        "value":1.62
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"",
                "value":0.4
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"",
                "value":0.26
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"稀有金属II,0.76%",
                "value":0.76
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#7987CB"
                },
                "name":"工业金属II,0.61%",
                "value":0.61
            }
        ],
        "index":5,
        "itemStyle":{
            "color":"#7987CB"
        },
        "name":"有色金属I,2.03%",
        "value":2.03
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"元件II,1.71%",
                "value":1.71
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"电子制造II,1.37%",
                "value":1.37
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"半导体II,0.88%",
                "value":0.88
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"光学光电子II,1.71%",
                "value":1.71
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#66B5F3"
                },
                "name":"其他电子II,0.78%",
                "value":0.78
            }
        ],
        "index":6,
        "itemStyle":{
            "color":"#66B5F3"
        },
        "name":"电子I,6.45%",
        "value":6.45
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#50C2F9"
                },
                "name":"白色家电II,1.31%",
                "value":1.31
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#50C2F9"
                },
                "name":"",
                "value":0.16
            }
        ],
        "index":7,
        "itemStyle":{
            "color":"#50C2F9"
        },
        "name":"",
        "value":1.47
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4DD1E2"
                },
                "name":"饮料制造II,1.99%",
                "value":1.99
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4DD1E2"
                },
                "name":"食品加工II,1.73%",
                "value":1.73
            }
        ],
        "index":8,
        "itemStyle":{
            "color":"#4DD1E2"
        },
        "name":"食品饮料I,3.72%",
        "value":3.72
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4FB4AD"
                },
                "name":"",
                "value":0.27
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4FB4AD"
                },
                "name":"",
                "value":0.49
            }
        ],
        "index":9,
        "itemStyle":{
            "color":"#4FB4AD"
        },
        "name":"",
        "value":0.76
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"造纸II,0.5%",
                "value":0.5
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.38
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.2
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#81C686"
                },
                "name":"",
                "value":0.0
            }
        ],
        "index":10,
        "itemStyle":{
            "color":"#81C686"
        },
        "name":"",
        "value":1.08
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"化学制药II,5.89%",
                "value":5.89
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医疗服务II,1.82%",
                "value":1.82
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"生物制品II,3.28%",
                "value":3.28
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医疗器械II,1.93%",
                "value":1.93
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"中药II,2.99%",
                "value":2.99
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#B0D482"
                },
                "name":"医药商业II,1.44%",
                "value":1.44
            }
        ],
        "index":11,
        "itemStyle":{
            "color":"#B0D482"
        },
        "name":"医药生物I,17.35%",
        "value":17.35
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"电力II,2.61%",
                "value":2.61
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"水务II,0.56%",
                "value":0.56
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"环保工程及服务II,1.09%",
                "value":1.09
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#DCE877"
                },
                "name":"",
                "value":0.09
            }
        ],
        "index":12,
        "itemStyle":{
            "color":"#DCE877"
        },
        "name":"公用事业I,4.35%",
        "value":4.35
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.29
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"高速公路II,0.83%",
                "value":0.83
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.48
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"港口II,0.55%",
                "value":0.55
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.32
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.27
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.17
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FFF177"
                },
                "name":"",
                "value":0.04
            }
        ],
        "index":13,
        "itemStyle":{
            "color":"#FFF177"
        },
        "name":"交通运输I,2.95%",
        "value":2.95
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FCDB62"
                },
                "name":"房地产开发II,4.17%",
                "value":4.17
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FCDB62"
                },
                "name":"",
                "value":0.41
            }
        ],
        "index":14,
        "itemStyle":{
            "color":"#FCDB62"
        },
        "name":"房地产I,4.58%",
        "value":4.58
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.24
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"一般零售II,0.61%",
                "value":0.61
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.17
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FDB84D"
                },
                "name":"",
                "value":0.1
            }
        ],
        "index":15,
        "itemStyle":{
            "color":"#FDB84D"
        },
        "name":"",
        "value":1.12
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.34
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.4
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FD8B66"
                },
                "name":"",
                "value":0.35
            }
        ],
        "index":16,
        "itemStyle":{
            "color":"#FD8B66"
        },
        "name":"",
        "value":1.09
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#BEBEBE"
                },
                "name":"",
                "value":0.4
            }
        ],
        "index":17,
        "itemStyle":{
            "color":"#BEBEBE"
        },
        "name":"",
        "value":0.4
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"",
                "value":0.3
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"水泥制造II,0.67%",
                "value":0.67
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#91A4AE"
                },
                "name":"",
                "value":0.26
            }
        ],
        "index":18,
        "itemStyle":{
            "color":"#91A4AE"
        },
        "name":"",
        "value":1.23
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.22
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.41
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"基础建设II,0.52%",
                "value":0.52
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.15
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#A38680"
                },
                "name":"",
                "value":0.15
            }
        ],
        "index":19,
        "itemStyle":{
            "color":"#A38680"
        },
        "name":"",
        "value":1.45
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"电源设备II,2.52%",
                "value":2.52
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"电气自动化设备II,0.53%",
                "value":0.53
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"高低压设备II,0.81%",
                "value":0.81
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#2196F3"
                },
                "name":"",
                "value":0.2
            }
        ],
        "index":20,
        "itemStyle":{
            "color":"#2196F3"
        },
        "name":"电气设备I,4.06%",
        "value":4.06
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.44
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.15
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.12
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#02AAF3"
                },
                "name":"",
                "value":0.33
            }
        ],
        "index":21,
        "itemStyle":{
            "color":"#02AAF3"
        },
        "name":"",
        "value":1.04
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#01BCD6"
                },
                "name":"计算机应用II,3.66%",
                "value":3.66
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#01BCD6"
                },
                "name":"计算机设备II,0.65%",
                "value":0.65
            }
        ],
        "index":22,
        "itemStyle":{
            "color":"#01BCD6"
        },
        "name":"计算机I,4.31%",
        "value":4.31
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"互联网传媒II,4.2%",
                "value":4.2
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"营销传播II,1.09%",
                "value":1.09
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#009786"
                },
                "name":"文化传媒II,3.23%",
                "value":3.23
            }
        ],
        "index":23,
        "itemStyle":{
            "color":"#009786"
        },
        "name":"传媒I,8.52%",
        "value":8.52
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#4EAF51"
                },
                "name":"通信设备II,1.66%",
                "value":1.66
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#4EAF51"
                },
                "name":"",
                "value":0.05
            }
        ],
        "index":24,
        "itemStyle":{
            "color":"#4EAF51"
        },
        "name":"通信I,1.71%",
        "value":1.71
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#8CC249"
                },
                "name":"银行II,5.45%",
                "value":5.45
            }
        ],
        "index":25,
        "itemStyle":{
            "color":"#8CC249"
        },
        "name":"银行I,5.45%",
        "value":5.45
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"保险II,2.59%",
                "value":2.59
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"证券II,6.56%",
                "value":6.56
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#CCDE37"
                },
                "name":"多元金融II,0.6%",
                "value":0.6
            }
        ],
        "index":26,
        "itemStyle":{
            "color":"#CCDE37"
        },
        "name":"非银金融I,9.75%",
        "value":9.75
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"汽车整车II,1.38%",
                "value":1.38
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"汽车零部件II,1.35%",
                "value":1.35
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"",
                "value":0.13
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FACD20"
                },
                "name":"",
                "value":0.11
            }
        ],
        "index":27,
        "itemStyle":{
            "color":"#FACD20"
        },
        "name":"汽车I,2.97%",
        "value":2.97
    },
    {
        "children":[
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"专用设备II,1.93%",
                "value":1.93
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"通用机械II,0.55%",
                "value":0.55
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.23
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.1
            },
            {
                "children":[],
                "itemStyle":{
                    "color":"#FF5723"
                },
                "name":"",
                "value":0.05
            }
        ],
        "index":28,
        "itemStyle":{
            "color":"#FF5723"
        },
        "name":"机械设备I,2.86%",
        "value":2.86
    }
]
}